### ISSUE TITLE
Use sign function to modify noise

### ISSUE THREAD

**Issue by lxxue** [kenny-co/procedural-advml#1]
Hi, thank you for the interesting paper and releasing the code.
I notice that there is a line of code in the `perturb` function:
`    noise = np.sign(noise) * max_norm`
This makes the line in the noise more sharp, right?
I wonder if you have investigated how many benefits this trick gained (in terms of query efficiency, lower max_norm, etc.)? Does this mean higher frequency will help attacking?

**Comment by kenny-co** [comment]
Because the perturbation was constrained to an L-infinity norm, the idea was to make the magnitude of the noise as large as possible by using the sgn function. With regards to what noise leads to stronger attacks, it's still an ongoing research problem.
